language: node_js

os: linux

node_js:
  - node

dist: trusty

sudo: required

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g @angular/cli@12.2.13
  - npm install

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test
  - npm run build:portal
  - cd dist/portal
  - cp index.html

branches:
  only:
    - master

env:
  - EMBER_VERSION=release

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN_TRAVIS
  local_dir: dist/portal
  on:
    branch: master
